Repository rcmaehl/WhyNotWin11, pull requests merged in 2021-06, with the labels that each got.

#104 Chinese(Simplified) translation
  Langs/0804.lang
Labels: awaiting reporter

#122 Added Italian Translation
  Langs/0410.lang
Labels: awaiting reporter

#142 Spanish Translation
  Langs/1034.lang
Labels: awaiting reporter

#125 040D - Hebrew Translation for the application
  Langs/040D
Labels: awaiting reporter

#135 Japanese translation
  Langs/0411.lang
  WhyNotWin11.au3
Labels: awaiting reporter

#92 CI improvements
  .github/workflows/wnw11.yml
Labels: awaiting reporter, enhancement

#203 [🇹🇷 - 📝] Translation issue fixed.
  Langs/1055.lang
Labels: awaiting reporter

#200 Add Polish translation
  Langs/0415.lang
Labels: awaiting reporter

#226 #217 Fix french translation texts are too long
  Langs/040C.lang
  Langs/1036.lang
  WhyNotWin11.au3
Labels: awaiting reporter

#218 Norwegian bokmål
  Langs/0414.lang
Labels: awaiting reporter

#281 support for running not compiled scirpt
  WhyNotWin11.au3
Labels: enhancement

#228 Add Hungarian translation
  Langs/1038.lang
Labels: awaiting reporter

#264 Spanish Translations
  Langs/080A.lang
  Langs/100A.lang
  Langs/140A.lang
  Langs/180A.lang
  Langs/1C0A.lang
  Langs/200A.lang
  Langs/240A.lang
  Langs/280A.lang
  Langs/2C0A.lang
  Langs/300A.lang
  Langs/340A.lang
  Langs/380A.lang
  Langs/3C0A.lang
  Langs/400A.lang
  Langs/440A.lang
  Langs/480A.lang
  Langs/4C0A.lang
  Langs/500A.lang
  Langs/540A.lang
Labels: awaiting reporter
