Repository rcmaehl/WhyNotWin11, pull requests merged in 2021-07, with the labels that each got.

#269 Improve Japanese translation
  Langs/0411.lang
Labels: awaiting reporter

#266 Update 0804.lang
  Langs/0804.lang
Labels: awaiting reporter

#288 Fix typo
  Langs/0408.lang
Labels: awaiting reporter

#322 Refactor CPU compatibility check code
  WhyNotWin11.au3
Labels: enhancement

#258 Added accessibility for users with screen readers.
  WhyNotWin11.au3
  includes/WhyNotWin11_accessibility.au3
  includes/jfw.au3
  includes/kbc.au3
  includes/reader.au3
  includes/sapi.au3
Labels: enhancement

#435 Update 0405.lang
  Langs/0405.lang
Labels: in-progress
